import { useState, useRef } from 'react';
import { IntegrationTask } from '../types';
import { playClickSound, playPageTurnSound } from '../utils/audio';
import { 
  Copy, 
  Download, 
  FileCode, 
  Check, 
  Calendar, 
  BookOpen, 
  CheckSquare, 
  Maximize2, 
  Compass, 
  HelpCircle,
  FileText 
} from 'lucide-react';

interface TaskDetailsProps {
  task: IntegrationTask;
  onUpdateStatus: (id: string, status: 'Planning' | 'Ready' | 'Completed') => void;
  onDelete: (id: string) => void;
}

export default function TaskDetails({ task, onUpdateStatus, onDelete }: TaskDetailsProps) {
  const [copiedType, setCopiedType] = useState<'embed' | 'markdown' | null>(null);

  const { aiSuggestion } = task;

  const playSoundSelect = () => {
    playPageTurnSound();
  };

  const handleCopyEmbed = () => {
    if (!aiSuggestion?.embedHtml) return;
    playClickSound();
    navigator.clipboard.writeText(aiSuggestion.embedHtml);
    setCopiedType('embed');
    setTimeout(() => setCopiedType(null), 2500);
  };

  const generateMarkdown = () => {
    if (!aiSuggestion) return '';
    return `# iPad Tech Integration: ${task.topic}
**Grade Level:** ${task.gradeLevel} | **Subject:** ${task.subject}
**Status:** ${task.status} | **Date Planned:** ${task.plannedDate || 'Not specified'}

${task.ccssText ? `## Common Core Standard\n* ${task.ccssText}\n` : ''}
## Main ISTE Student Standard Alignment
* **${aiSuggestion.isteStudentStandard}**

## Summary Overview
${aiSuggestion.summary}

---

## Activity 1: Native Out-of-the-Box iPad App Experience
* **Activity Name:** ${aiSuggestion.activity1Name}
* **Core Tool:** ${aiSuggestion.activity1Tool}
* **Instructional Description:** ${aiSuggestion.activity1Description}

### Student Playbook Steps:
${aiSuggestion.activity1Steps.map((step, idx) => `${idx + 1}. ${step}`).join('\n')}

---

## Activity 2: Trusted, Free, Login-Free Web Tool
* **Activity Name:** ${aiSuggestion.activity2Name}
* **Core Tool:** ${aiSuggestion.activity2Tool}
* **Instructional Description:** ${aiSuggestion.activity2Description}

### Student Playbook Steps:
${aiSuggestion.activity2Steps.map((step, idx) => `${idx + 1}. ${step}`).join('\n')}

---

## Classroom Reflection & Workflow Suggestion
* **Teacher Prompt:** ${aiSuggestion.reflectionPrompt}

---
*Generated by iPad Tech Integration Task Board - Fully aligned with ISTE Student Standards and USA Common Core.*`;
  };

  const handleCopyMarkdown = () => {
    playClickSound();
    const md = generateMarkdown();
    navigator.clipboard.writeText(md);
    setCopiedType('markdown');
    setTimeout(() => setCopiedType(null), 2500);
  };

  const handleDownloadJson = () => {
    playClickSound();
    const cleanObject = {
      ...task,
      exportedAt: new Date().toISOString()
    };
    const blob = new Blob([JSON.stringify(cleanObject, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `ipad-plan-${task.topic.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div id={`details-${task.id}`} className="bg-white border-4 border-orange-500 rounded-3xl p-8 shadow-xl flex flex-col">
      {/* Header Info */}
      <div className="flex flex-col md:flex-row md:items-start justify-between border-b border-gray-200 pb-6 mb-6 gap-4">
        <div>
          <div className="flex flex-wrap items-center gap-2 mb-3">
            <span className="bg-orange-100 text-orange-700 px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-tighter">
              {task.gradeLevel}
            </span>
            <span className="bg-gray-100 text-gray-800 px-3 py-1 rounded-full text-[10px] font-black uppercase tracking-tighter">
              {task.subject}
            </span>
          </div>
          <h1 id="details-topic-title" className="text-3xl md:text-4xl font-display font-black leading-tight text-neutral-900 uppercase italic">
            {task.topic}
          </h1>
          <p className="text-xs text-gray-400 font-bold uppercase tracking-widest mt-2">
            Plan ID: #001-{task.id.slice(-4).toUpperCase()} • Created: {new Date(task.createdAt).toLocaleDateString()}
          </p>
        </div>

        {/* Action Toggle State */}
        <div className="flex flex-wrap items-center gap-2">
          <div>
            <label htmlFor="state-select" className="sr-only">Lesson Status</label>
            <select
              id="state-select"
              value={task.status}
              onChange={(e) => {
                playSoundSelect();
                onUpdateStatus(task.id, e.target.value as any);
              }}
              className="bg-white border-2 border-gray-200 rounded-xl px-4 py-2.5 text-xs text-neutral-800 font-bold uppercase tracking-wide focus:outline-none focus:border-orange-500 cursor-pointer animate-none"
            >
              <option value="Planning">📝 Planning</option>
              <option value="Ready">⚡ Ready</option>
              <option value="Completed">✅ Done</option>
            </select>
          </div>

          <button
            id="btn-delete-task"
            onClick={() => {
              playClickSound();
              if (confirm('Are you sure you want to archive or delete this iPad tech lesson?')) {
                onDelete(task.id);
              }
            }}
            className="px-4 py-2.5 border-2 border-red-200 hover:bg-red-50 text-red-600 rounded-xl text-xs font-black uppercase tracking-wide transition-colors cursor-pointer"
          >
            Delete
          </button>
        </div>
      </div>

      {/* Standard Metadata Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
        {task.ccssText ? (
          <div className="bg-gray-50 border-2 border-gray-200 rounded-3xl p-6 shadow-sm">
            <h3 className="block text-[10px] font-black uppercase text-gray-400 mb-2 tracking-widest flex items-center gap-1">
              <BookOpen className="w-3.5 h-3.5" />
              Common Core Target
            </h3>
            <p className="text-sm font-semibold text-neutral-800 leading-relaxed font-sans">
              {task.ccssText}
            </p>
          </div>
        ) : (
          <div className="bg-gray-50 border-2 border-gray-200 rounded-3xl p-6 shadow-sm flex items-center justify-center text-center">
            <p className="text-xs text-gray-400 font-bold uppercase tracking-wider italic">
              No specific Common Core standard bound.
            </p>
          </div>
        )}

        {aiSuggestion && (
          <div className="bg-orange-50/50 border-2 border-orange-100 rounded-3xl p-6">
            <h3 className="block text-[10px] font-black uppercase text-orange-400 mb-2 tracking-widest flex items-center gap-1">
              <Compass className="w-3.5 h-3.5 text-orange-500" />
              ISTE Standard Highlight
            </h3>
            <p className="text-sm font-black text-orange-950 uppercase italic leading-tight">
              {aiSuggestion.isteStudentStandard}
            </p>
            <p className="text-[11px] text-orange-800 mt-2 leading-relaxed">
              Provides digital tools enabling active construction, creativity, and expressive voice.
            </p>
          </div>
        )}
      </div>

      {/* Teacher Notes if any */}
      {task.teacherNotes && (
        <div className="mb-6 bg-amber-50/50 border-2 border-amber-100 rounded-3xl p-6">
          <h4 className="block text-[10px] font-black uppercase text-amber-500 mb-2 tracking-widest">
            Instructional Coach & Needs Context
          </h4>
          <p className="text-sm text-neutral-700 italic leading-relaxed">" {task.teacherNotes} "</p>
        </div>
      )}

      {/* AI Suggestion Deck */}
      {aiSuggestion ? (
        <div className="space-y-6">
          {/* Summary Box */}
          <div className="bg-gray-50 border-2 border-gray-200 rounded-3xl p-6 flex flex-col justify-between shadow-sm">
            <h3 className="block text-[10px] font-black uppercase text-gray-400 mb-2 tracking-widest">
              Pedagogical Strategy Goal
            </h3>
            <p className="text-base text-gray-800 font-bold leading-relaxed font-sans italic">
              {aiSuggestion.summary}
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
            {/* Native App Experience */}
            <div className="bg-white border-2 border-gray-200 rounded-3xl p-6 flex flex-col hover:border-orange-500 transition-colors">
              <div className="flex justify-between items-start mb-3">
                <span className="bg-black text-white px-2.5 py-1 rounded-lg text-[9px] font-black uppercase tracking-widest text-[10px]">
                  Native iPad App
                </span>
                <span className="text-gray-400 font-mono text-xs">Phase 1</span>
              </div>

              <h4 className="text-[10px] font-black uppercase text-gray-400 tracking-widest mb-1">
                Out-Of-The-Box Expression
              </h4>
              <h3 className="text-xl font-display font-black uppercase italic tracking-tight text-neutral-900 mb-2">
                {aiSuggestion.activity1Name}
              </h3>

              <div className="text-xs font-black uppercase text-orange-600 mb-4 flex items-center gap-1.5">
                <span>⚡ TOOL: {aiSuggestion.activity1Tool}</span>
              </div>

              <p className="text-sm text-neutral-700 mb-6 leading-relaxed font-sans">
                {aiSuggestion.activity1Description}
              </p>

              <h5 className="block text-[10px] font-black uppercase text-gray-400 mb-3 tracking-widest">
                Student Lesson Checklist:
              </h5>
              <ol className="space-y-2.5 list-none p-0 m-0">
                {aiSuggestion.activity1Steps.map((step, idx) => (
                  <li key={idx} className="flex gap-2.5 text-sm text-neutral-700 font-semibold leading-relaxed">
                    <span className="flex-shrink-0 w-5 h-5 flex items-center justify-center bg-orange-500 text-black font-black rounded-lg text-xs">
                      {idx + 1}
                    </span>
                    <span>{step}</span>
                  </li>
                ))}
              </ol>
            </div>

            {/* Login-Free Web Experience */}
            <div className="bg-white border-2 border-gray-200 rounded-3xl p-6 flex flex-col hover:border-orange-500 transition-colors">
              <div className="flex justify-between items-start mb-3">
                <span className="bg-orange-100 text-orange-850 px-2.5 py-1 rounded-lg text-[9px] font-black uppercase tracking-widest text-[10px]">
                  Login-Free Simulation
                </span>
                <span className="text-gray-400 font-mono text-xs">Phase 2</span>
              </div>

              <h4 className="text-[10px] font-black uppercase text-gray-400 tracking-widest mb-1">
                Immediate Open Web Access
              </h4>
              <h3 className="text-xl font-display font-black uppercase italic tracking-tight text-neutral-900 mb-2">
                {aiSuggestion.activity2Name}
              </h3>

              <div className="text-xs font-black uppercase text-orange-600 mb-4 flex items-center gap-1.5">
                <span>🌐 WEB PORTAL: {aiSuggestion.activity2Tool}</span>
              </div>

              <p className="text-sm text-neutral-700 mb-6 leading-relaxed font-sans">
                {aiSuggestion.activity2Description}
              </p>

              <h5 className="block text-[10px] font-black uppercase text-gray-400 mb-3 tracking-widest">
                Student Lesson Checklist:
              </h5>
              <ol className="space-y-2.5 list-none p-0 m-0">
                {aiSuggestion.activity2Steps.map((step, idx) => (
                  <li key={idx} className="flex gap-2.5 text-sm text-neutral-700 font-semibold leading-relaxed">
                    <span className="flex-shrink-0 w-5 h-5 flex items-center justify-center bg-orange-500 text-black font-black rounded-lg text-xs">
                      {idx + 1}
                    </span>
                    <span>{step}</span>
                  </li>
                ))}
              </ol>
            </div>
          </div>

          {/* Workflow & Reflection Block */}
          <div className="bg-gray-900 border-2 border-gray-800 rounded-3xl p-6 text-white text-left">
            <h4 className="block text-[10px] font-black uppercase text-gray-500 mb-2 tracking-widest italic">
              Classroom Reflection & Exit Ticket Prompts
            </h4>
            <p className="text-base font-medium leading-snug">
              " {aiSuggestion.reflectionPrompt} "
            </p>
          </div>

        </div>
      ) : (
        <div className="py-12 text-center rounded-3xl bg-gray-50 border-2 border-gray-200">
          <HelpCircle className="w-12 h-12 text-neutral-300 mx-auto mb-3" />
          <h3 className="text-sm font-sans font-black uppercase text-neutral-500 tracking-wider">Plan Details Missing</h3>
          <p className="text-xs text-neutral-400 max-w-sm mx-auto mt-2 leading-relaxed">
            Please wait while your task configuration finishes generating inside our sandbox server.
          </p>
        </div>
      )}
    </div>
  );
}
